const T=window.CROVE_TOOLS||[], $=id=>document.getElementById(id);let fav=new Set(JSON.parse(localStorage.ct5fav||"[]")),recent=JSON.parse(localStorage.ct5recent||"[]"),mode="all",current=null,deferred=null;
function save(){localStorage.ct5fav=JSON.stringify([...fav]);localStorage.ct5recent=JSON.stringify(recent.slice(0,30))}
function render(){let q=$("search").value.toLowerCase(),box=$("list");box.innerHTML="";let cats={};for(let t of T){if(q&&!(`${t.name} ${t.cat}`).toLowerCase().includes(q))continue;if(mode==="fav"&&!fav.has(t.id))continue;if(mode==="recent"&&!recent.includes(t.id))continue;(cats[t.cat]??=[]).push(t)}for(let cat in cats){let s=document.createElement("section");s.className="category";s.innerHTML=`<h2>${cat}</h2><div class="grid"></div>`;for(let t of cats[cat]){let b=document.createElement("button");b.className="tool";b.innerHTML=`<button class="star">${fav.has(t.id)?"★":"☆"}</button><b>${t.name}</b><span>在线工具</span>`;b.onclick=e=>e.target.classList.contains("star")?(e.stopPropagation(),toggle(t.id)):open(t);s.querySelector(".grid").appendChild(b)}box.appendChild(s)}if(!box.children.length)box.innerHTML='<div class="out">没有找到工具</div>'}
function toggle(id){fav.has(id)?fav.delete(id):fav.add(id);save();render();if(current)$("favorite").textContent=fav.has(current.id)?"★":"☆"}
function open(t){current=t;recent=[t.id,...recent.filter(x=>x!==t.id)];save();$("title").textContent=t.name;$("favorite").textContent=fav.has(t.id)?"★":"☆";$("tool").innerHTML=ui(t.name);$("modal").classList.remove("hidden");bind(t.name)}
function ui(n){let ta='<textarea id="x" placeholder="请输入内容…"></textarea>',o='<div class="out" id="o"></div>';
if(n==="字数统计")return ta+'<div class="stats"><div class="stat"><b id="c">0</b>字符</div><div class="stat"><b id="w">0</b>词</div><div class="stat"><b id="l">0</b>行</div><div class="stat"><b id="by">0</b>字节</div></div>';
if(["文本去重","文本排序","空白清理","文本反转","行号添加","行号删除","重复行查找","空行删除","字符频率","词频统计","Tab 转空格"].includes(n))return ta+'<button class="primary" id="go">处理</button>'+o;
if(n==="大小写转换")return ta+'<button class="primary" id="upper">大写</button><button id="lower">小写</button><button id="titleCase">首字母</button>'+o;
if(n==="查找替换")return ta+'<input id="a" placeholder="查找"><input id="b" placeholder="替换为"><button class="primary" id="go">替换</button>'+o;
if(n==="正则测试")return '<input id="p" placeholder="正则表达式"><input id="rt" placeholder="测试文本"><input id="flags" value="g"><button class="primary" id="go">测试</button>'+o;
if(n==="JSON 格式化")return ta+'<button class="primary" id="fmt">格式化</button><button id="min">压缩</button>'+o;
if(n==="Base64"||n==="URL 编解码"||n==="Unicode"||n==="ASCII"||n==="HTML 转义"||n==="XML 转义"||n==="Hex 编解码"||n==="二进制编解码")return ta+'<button class="primary" id="enc">编码</button><button id="dec">解码</button>'+o;
if(["Hash","SHA256","SHA512","SHA-1","SHA-384","SHA-224"].includes(n))return ta+'<button class="primary" id="go">计算 Hash</button>'+o;
if(n==="JWT 查看")return ta+'<button class="primary" id="go">解析 Payload</button>'+o;
if(n==="进制转换")return '<input id="x" value="255"><select id="from"><option value="2">二进制</option><option value="8">八进制</option><option value="10">十进制</option><option value="16">十六进制</option></select><select id="to"><option value="2">二进制</option><option value="8">八进制</option><option value="10">十进制</option><option value="16">十六进制</option></select><button class="primary" id="go">转换</button>'+o;
if(n==="密码生成"||n==="随机字符串")return '<label>长度</label><input id="num" type="number" value="20" min="4" max="256"><button class="primary" id="go">生成</button>'+o;
if(n==="随机数")return '<input id="a" type="number" value="1" placeholder="最小"><input id="b" type="number" value="100" placeholder="最大"><button class="primary" id="go">生成</button>'+o;
if(n==="密码强度")return '<input id="x" type="password" placeholder="密码"><button class="primary" id="go">检测</button>'+o;
if(n==="随机 UUID 批量")return '<input id="num" type="number" value="10" min="1" max="100"><button class="primary" id="go">生成</button>'+o;
if(n==="二维码")return '<input id="x" placeholder="文字或 URL"><select id="size"><option>200</option><option selected>300</option><option>500</option></select><button class="primary" id="go">生成二维码</button>'+o;
if(["图片 Base64","图片信息","图片预览","图片压缩","图片缩放","转 PNG","转 JPEG","灰度","旋转","镜像","图片取色"].includes(n))return imageUI(n);
if(n==="HTTP Header")return '<button class="primary" id="go">读取 Header</button>'+o;
if(n==="IP 查询"||n==="我的 IP")return '<button class="primary" id="go">查询公网 IP</button>'+o;
if(["DNS 查询","DNS A","DNS AAAA","DNS MX","DNS TXT"].includes(n))return '<input id="x" value="cloudflare.com"><select id="type"><option>A</option><option>AAAA</option><option>MX</option><option>TXT</option></select><button class="primary" id="go">查询 DNS</button>'+o;
if(n==="CF IP 测试")return '<input id="x" placeholder="例如 1.1.1.1"><button class="primary" id="go">测试</button>'+o;
if(n==="Cloudflare Trace"||n==="CF Trace")return '<button class="primary" id="go">获取 Trace</button>'+o;
if(["IPv4 转整数","IPv4 校验","IPv6 检查","MAC 检查","端口检查"].includes(n))return '<input id="x" placeholder="输入地址或端口"><button class="primary" id="go">校验/转换</button>'+o;
if(n==="科学计算器")return '<input id="x" placeholder="例如 (12+5)*3/2"><button class="primary" id="go">计算</button>'+o;
if(n==="日期计算")return '<input id="a" type="date"><input id="b" type="date"><button class="primary" id="go">计算天数</button>'+o;
if(n==="百分比")return '<input id="a" type="number" value="20"><input id="b" type="number" value="100"><button class="primary" id="go">计算</button>'+o;
if(n==="平均值")return ta+'<button class="primary" id="go">统计</button>'+o;
if(n==="BMI")return '<input id="h" type="number" placeholder="身高 cm"><input id="w" type="number" placeholder="体重 kg"><button class="primary" id="go">计算 BMI</button>'+o;
if(["简单利息","复利"].includes(n))return '<input id="p" type="number" placeholder="本金"><input id="r" type="number" placeholder="年利率 %"><input id="y" type="number" placeholder="年数"><button class="primary" id="go">计算</button>'+o;
if(["温度转换"].includes(n))return '<input id="x" type="number" value="0"><select id="from"><option>C</option><option>F</option><option>K</option></select><select id="to"><option>F</option><option>C</option><option>K</option></select><button class="primary" id="go">转换</button>'+o;
if(["TXT 下载","文本下载"].includes(n))return ta+'<input id="name" value="crove.txt"><button class="primary" id="go">下载</button>'+o;
if(n==="文件信息"||n==="文件 Base64")return '<input id="f" type="file">'+o;
if(n==="文件 Hash")return '<input id="f" type="file"><select id="alg"><option>SHA-256</option><option>SHA-1</option><option>SHA-384</option><option>SHA-512</option></select><button class="primary" id="go">选择文件并计算</button>'+o;
if(n==="JSON 文件"||n==="CSV 生成")return ta+'<input id="name" value="'+(n==="JSON 文件"?"data.json":"data.csv")+'"><button class="primary" id="go">下载</button>'+o;
if(n==="设备信息"||n==="在线状态"||n==="浏览器语言"||n==="屏幕信息"||n==="时区信息"||n==="当前时间"||n==="随机颜色"||n==="LocalStorage"||n==="User-Agent"||n==="UA 解析"||n==="网络信息")return '<button class="primary" id="go">读取信息</button>'+o;
if(n==="网页分享")return '<button class="primary" id="go">分享/复制链接</button>'+o;
if(n==="颜色选择器")return '<input id="p" type="color" value="#6366f1"><div class="out" id="o">#6366f1</div>';
if(n==="Emoji")return '<div class="out" style="font-size:28px">😀 😃 😄 😁 😂 🤣 😊 😎 🚀 ⭐ 🔥 ❤️ 👍 🎉 💻 🌐 ☁️ 🔧 📱</div>';
if(n==="PWA 安装")return '<div class="out">Android/Chrome：点击右上角「📲 安装」。<br>iPhone/iPad：Safari → 分享 → 添加到主屏幕。</div>';
return '<input id="x" placeholder="输入内容…"><button class="primary" id="go">运行</button>'+o}
function imageUI(n){let o='<div class="out" id="o"></div>';if(n==="图片缩放")return '<input id="f" type="file" accept="image/*"><input id="iw" type="number" placeholder="目标宽 px"><input id="ih" type="number" placeholder="目标高 px"><label><input id="keep" type="checkbox" checked style="width:auto"> 按比例</label><button class="primary" id="go">选择图片并缩放</button>'+o;if(n==="图片压缩")return '<input id="f" type="file" accept="image/*"><label>质量：<span id="qv">80%</span></label><input id="q" type="range" min="10" max="100" value="80"><button class="primary" id="go">选择图片并压缩</button>'+o;if(n==="旋转")return '<input id="f" type="file" accept="image/*"><select id="angle"><option value="90">顺时针 90°</option><option value="180">180°</option><option value="270">顺时针 270°</option></select><button class="primary" id="go">选择图片并旋转</button>'+o;if(n==="灰度")return '<input id="f" type="file" accept="image/*"><button class="primary" id="go">选择图片并灰度</button>'+o;if(n==="镜像")return '<input id="f" type="file" accept="image/*"><select id="axis"><option value="x">水平镜像</option><option value="y">垂直镜像</option></select><button class="primary" id="go">选择图片并镜像</button>'+o;if(n==="图片取色")return '<input id="f" type="file" accept="image/*"><p class="hint">选择图片后点击图片。</p><canvas id="canvas" style="max-width:100%;width:100%"></canvas>'+o;if(n==="图片预览")return '<input id="f" type="file" accept="image/*"><div id="o"></div>';return '<input id="f" type="file" accept="image/*"><p class="hint">选择图片后自动处理。</p>'+o}
function dl(b,n){let a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function hash(a,d){let r=await crypto.subtle.digest(a,typeof d==="string"?new TextEncoder().encode(d):d);return [...new Uint8Array(r)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function bind(n){let x=$("x"),o=$("o");
if(n==="字数统计")x.oninput=()=>{c.textContent=x.value.length;w.textContent=(x.value.trim().match(/\S+/g)||[]).length;l.textContent=x.value?x.value.split("\n").length:0;by.textContent=new Blob([x.value]).size};
if(["文本去重","文本排序","空白清理","文本反转","行号添加","行号删除","重复行查找","空行删除","字符频率","词频统计","Tab 转空格"].includes(n))go.onclick=()=>{let a=x.value.split(/\r?\n/);if(n==="文本去重")a=[...new Set(a)];if(n==="文本排序")a.sort((p,q)=>p.localeCompare(q,"zh-CN"));if(n==="空白清理"||n==="空行删除")a=a.map(v=>v.trim()).filter(Boolean);if(n==="文本反转")o.textContent=[...x.value].reverse().join("");else if(n==="行号添加")o.textContent=a.map((v,i)=>`${i+1}. ${v}`).join("\n");else if(n==="行号删除")o.textContent=x.value.replace(/^\s*\d+[.)]\s?/gm,"");else if(n==="重复行查找")o.textContent=[...new Set(a.filter((v,i)=>v&&a.indexOf(v)!==i))].join("\n");else if(n==="字符频率"||n==="词频统计"){let z=n==="字符频率"?[...x.value.replace(/\s/g,"")]:x.value.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[],m={};z.forEach(v=>m[v]=(m[v]||0)+1);o.textContent=Object.entries(m).sort((p,q)=>q[1]-p[1]).map(v=>v[0]+": "+v[1]).join("\n")}else if(n==="Tab 转空格")o.textContent=x.value.replace(/\t/g,"    ");else o.textContent=a.join("\n")};
if(n==="大小写转换"){upper.onclick=()=>o.textContent=x.value.toUpperCase();lower.onclick=()=>o.textContent=x.value.toLowerCase();titleCase.onclick=()=>o.textContent=x.value.replace(/\b\w/g,v=>v.toUpperCase())}
if(n==="查找替换")go.onclick=()=>o.textContent=x.value.split(a.value).join(b.value);
if(n==="正则测试")go.onclick=()=>{try{let r=new RegExp(p.value,flags.value),m=[...rt.value.matchAll(r)];o.textContent=`匹配数：${m.length}\n${m.map(v=>v[0]).join("\n")}`}catch(e){o.textContent=e.message}};
if(n==="JSON 格式化"){fmt.onclick=()=>{try{o.textContent=JSON.stringify(JSON.parse(x.value),null,2)}catch(e){o.textContent=e.message}};min.onclick=()=>{try{o.textContent=JSON.stringify(JSON.parse(x.value))}catch(e){o.textContent=e.message}}}
if(["Base64","URL 编解码","Unicode","ASCII","HTML 转义","XML 转义","Hex 编解码","二进制编解码"].includes(n)){enc.onclick=()=>{if(n==="Base64")o.textContent=btoa(unescape(encodeURIComponent(x.value)));else if(n==="URL 编解码")o.textContent=encodeURIComponent(x.value);else if(n==="Unicode")o.textContent=[...x.value].map(c=>"\\u"+c.codePointAt(0).toString(16).padStart(4,"0")).join("");else if(n==="ASCII")o.textContent=[...x.value].map(c=>c.charCodeAt(0)).join(" ");else if(n==="Hex 编解码")o.textContent=[...x.value].map(c=>c.charCodeAt(0).toString(16).padStart(2,"0")).join("");else if(n==="二进制编解码")o.textContent=[...x.value].map(c=>c.charCodeAt(0).toString(2).padStart(8,"0")).join("");else o.textContent=x.value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")};dec.onclick=()=>{try{if(n==="Base64")o.textContent=decodeURIComponent(escape(atob(x.value)));else if(n==="URL 编解码")o.textContent=decodeURIComponent(x.value);else if(n==="Unicode")o.textContent=x.value.replace(/\\u([0-9a-f]{4})/gi,(_,h)=>String.fromCharCode(parseInt(h,16)));else if(n==="ASCII")o.textContent=x.value.trim().split(/\s+/).map(Number).map(v=>String.fromCharCode(v)).join("");else if(n==="Hex 编解码")o.textContent=(x.value.match(/.{1,2}/g)||[]).map(h=>String.fromCharCode(parseInt(h,16))).join("");else if(n==="二进制编解码")o.textContent=x.value.trim().split(/\s+/).map(v=>String.fromCharCode(parseInt(v,2))).join("");else o.textContent=x.value.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")}catch(e){o.textContent=e.message}}}
if(["Hash","SHA256","SHA512","SHA-1","SHA-384","SHA-224"].includes(n))go.onclick=async()=>o.textContent=await hash({"Hash":"SHA-256","SHA256":"SHA-256","SHA512":"SHA-512","SHA-1":"SHA-1","SHA-384":"SHA-384","SHA-224":"SHA-384"}[n],x.value);
if(n==="密码生成"||n==="随机字符串")go.onclick=()=>{let c=n==="密码生成"?"ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",a=new Uint32Array(+num.value);crypto.getRandomValues(a);o.textContent=[...a].map(v=>c[v%c.length]).join("")};
if(n==="随机数")go.onclick=()=>{let z=new Uint32Array(1);crypto.getRandomValues(z);o.textContent=Math.floor(z[0]/4294967296*(+b.value-+a.value+1))+ +a.value};
if(n==="密码强度")go.onclick=()=>{let s=x.value,k=(s.length>=8)+(/[a-z]/.test(s))+(/[A-Z]/.test(s))+( /\d/.test(s))+(/[^A-Za-z0-9]/.test(s));o.textContent="强度："+["很弱","弱","一般","强","很强","极强"][k]};
if(n==="随机 UUID 批量")go.onclick=()=>o.textContent=Array.from({length:+num.value},()=>crypto.randomUUID()).join("\n");
if(n==="二维码")go.onclick=()=>o.innerHTML=`<img class="preview" src="https://api.qrserver.com/v1/create-qr-code/?size=${size.value}x${size.value}&data=${encodeURIComponent(x.value)}">`;
if(n==="HTTP Header")go.onclick=async()=>o.textContent=await(await fetch("/api/headers")).text();
if(n==="IP 查询"||n==="我的 IP")go.onclick=async()=>o.textContent=await(await fetch("/api/ip")).text();
if(["DNS 查询","DNS A","DNS AAAA","DNS MX","DNS TXT"].includes(n))go.onclick=async()=>o.textContent=await(await fetch(`/api/dns?name=${encodeURIComponent(x.value)}&type=${n==="DNS MX"?"MX":n==="DNS TXT"?"TXT":n==="DNS AAAA"?"AAAA":"A"}`)).text();
if(n==="CF IP 测试")go.onclick=async()=>o.textContent=await(await fetch(`/api/cfip?ip=${encodeURIComponent(x.value)}`)).text();
if(n==="Cloudflare Trace"||n==="CF Trace")go.onclick=async()=>o.textContent=await(await fetch("/cdn-cgi/trace")).text();
if(n==="IPv4 校验")go.onclick=()=>o.textContent=/^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/.test(x.value)?"合法 IPv4":"非法 IPv4";
if(n==="IPv4 转整数")go.onclick=()=>o.textContent=x.value.split(".").map(Number).reduce((a,v)=>a*256+v,0);
if(n==="IPv6 检查")go.onclick=()=>o.textContent=x.value.includes(":")?"IPv6 格式初步通过":"不是 IPv6";
if(n==="MAC 检查")go.onclick=()=>o.textContent=/^([0-9a-f]{2}[:-]){5}[0-9a-f]{2}$/i.test(x.value)?"合法 MAC":"格式错误";
if(n==="端口检查")go.onclick=()=>o.textContent=(+x.value>=1&&+x.value<=65535)?"合法端口":"范围 1-65535";
if(n==="科学计算器")go.onclick=()=>{try{if(!/^[0-9+\-*/().%\s]+$/.test(x.value))throw Error("仅允许基础运算");o.textContent=Function('"use strict";return ('+x.value+')')()}catch(e){o.textContent=e.message}};
if(n==="日期计算")go.onclick=()=>o.textContent=Math.abs(new Date(b.value)-new Date(a.value))/86400000+" 天";
if(n==="百分比")go.onclick=()=>o.textContent=(+a.value/+b.value*100).toFixed(4)+"%";
if(n==="平均值")go.onclick=()=>{let z=x.value.split(/[,\s\n]+/).map(Number).filter(Number.isFinite);o.textContent=`总和：${z.reduce((a,b)=>a+b,0)}\n平均：${z.reduce((a,b)=>a+b,0)/z.length}`};
if(n==="BMI")go.onclick=()=>o.textContent=(+w.value/(+h.value/100)**2).toFixed(2);
if(n==="简单利息")go.onclick=()=>o.textContent=`利息：${+p.value*+r.value/100*+y.value}`;
if(n==="复利")go.onclick=()=>o.textContent=(+p.value*(1+ +r.value/100)**+y.value).toFixed(2);
if(n==="温度转换")go.onclick=()=>{let v=+x.value;if(from.value==="F")v=(v-32)*5/9;if(from.value==="K")v-=273.15;if(to.value==="F")v=v*9/5+32;if(to.value==="K")v+=273.15;o.textContent=v};
if(n==="进制转换")go.onclick=()=>{try{o.textContent=parseInt(x.value,+from.value).toString(+to.value).toUpperCase()}catch(e){o.textContent="输入无效"}};
if(n==="TXT 下载"||n==="文本下载")go.onclick=()=>dl(new Blob([x.value],{type:"text/plain;charset=utf-8"}),name.value||"crove.txt");
if(n==="JSON 文件"||n==="CSV 生成")go.onclick=()=>dl(new Blob([x.value],{type:n==="JSON 文件"?"application/json":"text/csv;charset=utf-8"}),name.value);
if(n==="文件信息")f.onchange=()=>{let z=f.files[0];o.textContent=`文件：${z.name}\n类型：${z.type||"未知"}\n大小：${z.size} bytes\n修改：${new Date(z.lastModified).toLocaleString()}`};
if(n==="文件 Base64")f.onchange=()=>{let r=new FileReader();r.onload=()=>o.textContent=r.result;r.readAsDataURL(f.files[0])};
if(n==="文件 Hash")go.onclick=async()=>{if(!f.files[0])return o.textContent="请先选择文件";o.textContent=await hash(alg.value,await f.files[0].arrayBuffer())};
if(n==="设备信息")go.onclick=()=>o.textContent=`平台：${navigator.platform}\n语言：${navigator.language}\n屏幕：${screen.width} × ${screen.height}\n像素比：${devicePixelRatio}`;
if(n==="在线状态")go.onclick=()=>o.textContent=navigator.onLine?"在线":"离线";
if(n==="浏览器语言")go.onclick=()=>o.textContent=navigator.language;
if(n==="屏幕信息")go.onclick=()=>o.textContent=`${screen.width} × ${screen.height}\n像素比：${devicePixelRatio}`;
if(n==="时区信息")go.onclick=()=>o.textContent=Intl.DateTimeFormat().resolvedOptions().timeZone;
if(n==="当前时间")go.onclick=()=>o.textContent=new Date().toLocaleString();
if(n==="随机颜色")go.onclick=()=>o.textContent="#"+Math.floor(Math.random()*16777215).toString(16).padStart(6,"0");
if(n==="LocalStorage")go.onclick=()=>o.textContent=JSON.stringify(localStorage,null,2);
if(n==="网页分享")go.onclick=async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else await navigator.clipboard.writeText(location.href);o.textContent="已分享/复制链接"}catch(e){o.textContent=e.message}};
if(n==="颜色选择器")p.oninput=()=>o.textContent=p.value;
if(["图片 Base64","图片信息","图片预览","图片压缩","图片缩放","转 PNG","转 JPEG","灰度","旋转","镜像"].includes(n))imageHandler(n);
if(n==="图片取色")colorPick();
}
function imageHandler(n){let f=$("f"),o=$("o");if(q)q.oninput=()=>qv.textContent=q.value+"%";let run=()=>{let file=f.files[0];if(!file){o.textContent="请先选择图片";return}if(n==="图片 Base64"){let r=new FileReader();r.onload=()=>o.textContent=r.result;r.readAsDataURL(file);return}let im=new Image();im.onload=()=>{if(n==="图片信息"){o.textContent=`文件：${file.name}\n类型：${file.type}\n大小：${file.size} bytes\n尺寸：${im.width} × ${im.height}`;return}if(n==="图片预览"){o.innerHTML=`<img class="preview" src="${URL.createObjectURL(file)}">`;return}let c=document.createElement("canvas"),w=im.width,h=im.height,a=0;if(n==="图片缩放"){let tw=+iw.value,th=+ih.value;if(keep.checked){if(tw&&!th){w=tw;h=Math.round(im.height*tw/im.width)}else if(th&&!tw){h=th;w=Math.round(im.width*th/im.height)}else if(tw&&th){let r=Math.min(tw/im.width,th/im.height);w=Math.round(im.width*r);h=Math.round(im.height*r)}}else{w=tw||w;h=th||h}}if(n==="旋转"){a=+angle.value;if(a===90||a===270)[w,h]=[h,w]}c.width=w;c.height=h;let ctx=c.getContext("2d");if(n==="旋转"){ctx.translate(w/2,h/2);ctx.rotate(a*Math.PI/180);ctx.drawImage(im,-im.width/2,-im.height/2)}else if(n==="镜像"){if(axis.value==="x"){ctx.translate(w,0);ctx.scale(-1,1)}else{ctx.translate(0,h);ctx.scale(1,-1)}ctx.drawImage(im,0,0,w,h)}else{if(n==="灰度")ctx.filter="grayscale(1)";ctx.drawImage(im,0,0,w,h)}let mime=(n==="图片压缩"||n==="转 JPEG")?"image/jpeg":"image/png";c.toBlob(b=>{dl(b,mime==="image/jpeg"?"crove.jpg":"crove.png");o.textContent=`处理完成：${w} × ${h}`},mime,n==="图片压缩"?+q.value/100:1)};im.src=URL.createObjectURL(file)};if(["图片 Base64","图片信息","图片预览"].includes(n))f.onchange=run;else go.onclick=run}
function colorPick(){let f=$("f");f.onchange=()=>{let im=new Image();im.onload=()=>{let c=$("canvas"),ctx=c.getContext("2d");c.width=im.width;c.height=im.height;ctx.drawImage(im,0,0);c.onclick=e=>{let r=c.getBoundingClientRect(),p=ctx.getImageData((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height,1,1).data;o.textContent=`rgb(${p[0]}, ${p[1]}, ${p[2]}) / #${[p[0],p[1],p[2]].map(v=>v.toString(16).padStart(2,"0")).join("")}`}};im.src=URL.createObjectURL(f.files[0])}}
$("search").oninput=render;document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;render()});$("favorite").onclick=()=>toggle(current.id);$("close").onclick=()=>$("modal").classList.add("hidden");$("modal").onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.classList.add("hidden")};
$("theme").onclick=()=>{document.body.classList.toggle("light");localStorage.ct5theme=document.body.classList.contains("light")?"light":"dark"};if(localStorage.ct5theme==="light")document.body.classList.add("light");
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{if(deferred){await deferred.prompt();deferred=null;$("install").classList.add("hidden")}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});render();